version: 2.1

executors:
  baseline_executor: # Baseline executor used by all the jobs
    working_directory: ~/blockfi-wp-relay

    docker:
      - image: circleci/buildpack-deps:stretch

commands:
  # Push to ECR
  docker_push: # Push the image to ECR, tagging as necessary
    description: "Push the image to ECR"
    steps:
      - run:
          name: Push images to ECR
          command: |
            set +o pipefail

            # Install aws_cli
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3-pip python3-dev
            pip3 install awscli

            # Login to AWS ECR
            $(aws ecr get-login --no-include-email --region us-east-1)

            # Push all the other branches anyhow
            docker tag ${CIRCLE_PROJECT_REPONAME} 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker push 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

            docker tag ${CIRCLE_PROJECT_REPONAME} 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:latest
            docker push 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:latest

            if [ "$CIRCLE_TAG" != "" ]; then
              docker tag ${CIRCLE_PROJECT_REPONAME} 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
              docker push 190058502420.dkr.ecr.us-east-1.amazonaws.com/blockfi/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            fi
            docker logout https://190058502420.dkr.ecr.us-east-1.amazonaws.com
#
# JOBS START HERE
#
jobs:
  # Build and push the Docker
  docker_build_and_push:
    executor: baseline_executor

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.03.1-ce
          docker_layer_caching: true

      - run:
          name: Make containers
          command: |
            docker build -t ${CIRCLE_PROJECT_REPONAME} -f Dockerfile .

      - docker_push

#
# WORKFLOWS START HERE
#

# The flow is
#
# start--|
#        |--------------------docker_build_and_push
#
workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - docker_build_and_push:
          context: blockfi_global
          filters:
            tags:
              only: /.*/
